[tool.isort]
known_first_party = ["ibllib", "iblutil", "one", "brainbox", "neurencoding"]
known_local_folder = ["delphi"]
import_heading_stdlib = "Standard library"
import_heading_thirdparty = "Third party libraries"
import_heading_firstparty = "IBL libraries"
import_heading_localfolder = "Brainwide repo imports"

[tool.yapf]
based_on_style = "google"
column_limit = 99
split_before_dot = true
